version: "3.4"
services:
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101315.2
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /config/redstone/run-execution-layer.sh
    env_file:
       - ./envs/redstone.env
    volumes:
      - ./data/:/data
      - ./config/:/config
    ports:
      - 8545:8545
      - 8546:8546
      - 8551:8551
      - 39393:39393/udp
      - 39393:39393/tcp
    extra_hosts:
      - "host.docker.internal:host-gateway"

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.8.0
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /config/redstone/run-consensus-layer.sh
    env_file:
       - ./envs/redstone.env
    volumes:
      - ./data/:/data
      - ./config/:/config
    ports:
      - 9003:9003/udp
      - 9003:9003/tcp
      - 9545:9545
    extra_hosts:
      - "host.docker.internal:host-gateway"

