# docker-compose.yml for running a garnet node
#
# Setup:
# 1. Edit .env to set L1_URL to an access point to Holesky
# 2. Run `docker compose -f garnet-compose.yml up -d`
version: "3.4"
services:
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101315.2
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /config/garnet/run-execution-layer.sh
    env_file:
       - .env
    volumes:
      - ./data/:/data
      - ./config/:/config
    ports:
      - 8545:8545
      - 8546:8546
      - 8551:8551
      - 39393:39393/udp
      - 39393:39393/tcp
    extra_hosts:
      - "host.docker.internal:host-gateway"

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.8.0
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /config/garnet/run-consensus-layer.sh
    env_file:
       - .env
    volumes:
      - ./data/:/data
      - ./config/:/config
    ports:
      - 9003:9003/udp
      - 9003:9003/tcp
      - 9545:9545
      - 8547:8547
    extra_hosts:
      - "host.docker.internal:host-gateway"

